### ISSUE TITLE
Is it support dragging outside the list?

### ISSUE THREAD

**Issue by rdmitrij** [mikewuu/react-beautiful-dnd-tester#9]
In every example I've find this code:

```js
const onDragEnd = (result: DropResult) => {
    if (!result.destination) {
      return
    }
  ...
}
```

Is it possible to execute onDragEnd handler without destination prop to cover this case by tests?

**Comment by mikewuu** [comment]
Don't think so. The only way I've seen `destination` be `null` was when the drag was ended off the browser window.

**Comment by rdmitrij** [comment]
I always catch this case if I move the card outside the droppable container

**Comment by mikewuu** [comment]
Via mouse though, right? Are you able to replicate this case via keyboard?
